### PR TITLE
idempotent start

### LINKED ISSUE #64: idempotent start
use case:
I'm using embedded-elasticsearch for tests, where some of the tests turn elasticsearch off to simulate errors, so that between any two tests i want to validate that the elasticsearch is back on again.
for that I use a reset method:
```scala
  def reset() = {
    embeddedElastic.start // theoretically idempotent
    embeddedElastic.deleteIndices
    embeddedElastic.createIndices
  }
```
I assume that the `start()` method in `EmbeddedElastic` is supposedly idempotent as far as the internal `ElasticServer` instance is concerned:  because I see that it's only calling the `.start()` method if it receives false on `isStarted()` :
```java
    private void startElastic() throws IOException, InterruptedException {
        if (!elasticServer.isStarted()) {
            elasticServer.start();
        }
    }
```
however, `isStarted()` is implemented by optimistically, lock-free reading the `started` flag:
```java
    boolean isStarted() {
        return started;
    }
```
and the `started` flag may have already been written to by another thread listening to the logs in `signalElasticStarted()`:
```java
    private void signalElasticStarted() {
        synchronized (startedLock) {
            started = true;
            startedLock.notifyAll();
        }
    }
```
I'm solving this locally by wrapping the `EmbeddedElastic` with a proxy that has idempotent `ensureStarted()` and `ensureStopped()` by means of its own `started` flag. I think this is a feature that is should move into `EmbeddedElastic` itself so that other users may enjoy mindlessly resetting the state of the server with no need to track who did what to it beforehand.

### PR DESCRIPTION
**Pull request by amir-arad**
make the `.start()` and `.stop()` methods of EmbeddedElastic Idempotent to themselves (consecutive calls to the same method from different threads will have no effect)

fixes #64

### CODE REVIEW

**Comment by amir-arad** [comment]
@gaczm I'm a novice in groovy and rusty in java concurrency. 
I did my best, and would appreciate review and feedback.

File: core/src/main/java/pl/allegro/tech/embeddedelasticsearch/EmbeddedElastic.java [hunk 1]
```diff
@@ -33,6 +33,8 @@
 
     private ElasticServer elasticServer;
     private ElasticRestClient elasticRestClient;
+    private boolean started = false;
```
Comment (gaczm) [inline core/src/main/java/pl/allegro/tech/embeddedelasticsearch/EmbeddedElastic.java]: Instead of two fields and DCL in start/stop methods, you can use AtomicBoolean. It will be much simpler

File: core/src/test/groovy/pl/allegro/tech/embeddedelasticsearch/SynchronicitySpec.groovy [hunk 2]
```diff
@@ -0,0 +1,38 @@
+package pl.allegro.tech.embeddedelasticsearch
+
+import spock.lang.Specification
+
+import static java.util.concurrent.TimeUnit.MINUTES
+
+class SynchronicitySpec extends Specification {
```
Comment (gaczm) [inline core/src/test/groovy/pl/allegro/tech/embeddedelasticsearch/SynchronicitySpec.groovy]: Well, this spec proofs nothing :/ You can make spec that will invoke start method second time with assertion noExceptionThrown()

**Comment by gaczm** [comment]
Thanks for your PR and sorry that it took so long :/ I've added comments, please look at them

File: core/src/test/groovy/pl/allegro/tech/embeddedelasticsearch/SynchronicitySpec.groovy (hunk 2 above)
Comment (amir-arad) [reply core/src/test/groovy/pl/allegro/tech/embeddedelasticsearch/SynchronicitySpec.groovy]: the test I've added failed before I wrote the implementation. A test that starts the server a second time from the same thread did not fail...

File: core/src/main/java/pl/allegro/tech/embeddedelasticsearch/EmbeddedElastic.java (hunk 1 above)
Comment (amir-arad) [reply core/src/main/java/pl/allegro/tech/embeddedelasticsearch/EmbeddedElastic.java]: I'm rusty on my java concurrency but I've used a synchronized block for a reason - to invalidate thread cache and flush other CPU cores / other thre that might have pending changes for that object. `AtomicBoolean` will not solve that AFAIK

Comment (gaczm) [reply core/src/main/java/pl/allegro/tech/embeddedelasticsearch/EmbeddedElastic.java]: What do you mean by "pending changes for that object"?

Comment (gaczm) [reply core/src/main/java/pl/allegro/tech/embeddedelasticsearch/EmbeddedElastic.java]: Now I see that both my proposition and your solution share same problem: when first thread reaches line which changes started state to true, second thread will finish method and think that Elasticsearch is ready, but it's not. 

I think it can be solved with something like this:

```
public EmbeddedElastic start() throws IOException, InterruptedException {
    synchronized (lifecycleLock) {
        if (!started) {
            installElastic();
            startElastic();
            createRestClient();
            createTemplates();
            createIndices();
            started = true; // started must be volatile
        }
    }
}

public void stop() {
    if (elasticServer != null) {
        synchronized (lifecycleLock) {
            if (started) {
                started = false;
                elasticServer.stop();
            }
        }
    }
}
```

BTW I think we might we can resign from lifecycleLock and simply make start/stop methods synchronized.

File: core/src/test/groovy/pl/allegro/tech/embeddedelasticsearch/SynchronicitySpec.groovy (hunk 2 above)
Comment (gaczm) [reply core/src/test/groovy/pl/allegro/tech/embeddedelasticsearch/SynchronicitySpec.groovy]: It will fail if you specify same http/transport port :)

File: core/src/main/java/pl/allegro/tech/embeddedelasticsearch/EmbeddedElastic.java (hunk 1 above)
Comment (amir-arad) [reply core/src/main/java/pl/allegro/tech/embeddedelasticsearch/EmbeddedElastic.java]: > BTW I think we might we can resign from lifecycleLock and simply make start/stop methods synchronized.

yes!

File: core/src/test/groovy/pl/allegro/tech/embeddedelasticsearch/SynchronicitySpec.groovy (hunk 2 above)
Comment (amir-arad) [reply core/src/test/groovy/pl/allegro/tech/embeddedelasticsearch/SynchronicitySpec.groovy]: maybe, but the test as I wrote it is closer to the scenario i'm facing (explained in #64)

File: core/src/main/java/pl/allegro/tech/embeddedelasticsearch/EmbeddedElastic.java [hunk 3]
```diff
@@ -33,6 +33,7 @@
...
```
Comment (gaczm) [inline core/src/main/java/pl/allegro/tech/embeddedelasticsearch/EmbeddedElastic.java]: this must be volatile

File: core/src/test/groovy/pl/allegro/tech/embeddedelasticsearch/SynchronicitySpec.groovy [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+    static final ELASTIC_VERSION = "2.2.0"
+
+    def "should not throw exception on starting embedded instance more than once from different threads"() {
+        when:
+        final server = EmbeddedElastic.builder()
+                .withElasticVersion(ELASTIC_VERSION)
+                .withStartTimeout(TEST_START_TIMEOUT_IN_MINUTES, MINUTES)
```
Comment (gaczm) [inline core/src/test/groovy/pl/allegro/tech/embeddedelasticsearch/SynchronicitySpec.groovy]: As I said in previous comment: you have to specify http/transport port. Without this embedded-elasticsearch might start twice without your mechanism

**Comment by gaczm** [comment]
It looks fine now :) I will release it as 2.7.1 soon
